### ISSUE TITLE
New access rights for new members

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/CrashReportImporter#1]
Hi @TheAssassin,

as we have some new Members at TeamNewPipe, namely @yausername @karyogamy  @nv95 id like to suggest them to get access to [sentry.schabi.org](https://sentry.schabi.org). What do you think, could you handle this?

**Comment by TheAssassin** [comment]
Yes. Please send them over to IRC where they send me an email address in a private message that I can register. Or have them send me an email directly.

**Comment by theScrabi** [comment]
Optionally an email can be send to schabi@schabi.org.

**Comment by TheAssassin** [comment]
Closing as resolved.
