### ISSUE TITLE
Remove unused "ip_range" field from Sentry

### ISSUE THREAD

**Issue by mauriciocolli** [TeamNewPipe/CrashReportImporter#3]
It was discussed and removed over NewPipe, in the issue TeamNewPipe/NewPipe/issues/1148.

@TheAssassin You mentioned that you were going to remove them ([they're still here](https://github.com/TeamNewPipe/CrashReportImporter/blob/75d930812ac689eee8bb5fe09354ac7be47213c2/newpipe_crash_report_importer/storage.py#L274)), maybe this was forgotten?

**Comment by TheAssassin** [comment]
Most likely I just forgot. Please feel free to remove them in a PR.
